### ISSUE TITLE
RenameTarget fails... This is potentially when they're in a group

### ISSUE THREAD

**Issue by BCAdler** [KCarretto/Arsenal#114]
![image](https://user-images.githubusercontent.com/14829389/38544210-d1dae708-3c74-11e8-9a5e-fd71c1f26079.png)

**Comment by KCarretto** [comment]
This was the result of GroupAutomember rules. The code for migrating the Target's groups was not updated, and so it was guaranteed to raise a MembershipError if the target was in any groups while being renamed. Session's "broke" because they were set to point to the target's new name, while the unhandled MembershipError prevented the target from ever being renamed.
